public abstract class DataConfig {
    static public String[] aoiNames = {
        "AI",
        "No AOI",
        "Alt_VSI",
        "ASI",
        "Window",
        "SSI",
        "TI_HSI",
        "RPM"
    };

    static public String[] participantID = {
        "p1",
        "p10",
        "p11",
        "p12",
        "p14",
        "p15",
        "p16",
        "p17",
        "p18",
        "p19",
        "p2",
        "p21",
        "p22",
        "p23",
        "p24",
        "p26",
        "p28",
        "p29",
        "p3",
        "p30",
        "p31",
        "p32",
        "p33",
        "p34",
        "p36",
        "p37",
        "p38",
        "p39",
        "p40",
        "p41",
        "p42",
        "p43",
        "p44",
        "p46",
        "p47",
        "p5",
        "p7",
        "p8",
        "p9"
    };

}
